version: "3.9"
services:
  web:
    image: nvidia/cuda:8.0-devel-ubuntu14.04
    cap_add:
      - SYS_PTRACE
      - CAP_SYS_ADMIN
    tty: true
    volumes:
      - .:/app/project
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
